### ISSUE TITLE
Error saving API Key and Client ID

### ISSUE THREAD

**Issue by vseager** [vincent2090311/magento2-campaignmonitor#2]
When saving the configuration I get the following error:
```
Something went wrong while saving this configuration: Warning: call_user_func_array() expects parameter 2 to be array, boolean given in /var/www/vendor/luma/module-campaignmonitor/Helper/Data.php on line 180
```

The API Key and Client ID does save, but the "Select a List" dropdown isn't populated. See the attached screenshot.

![screenshot-2018 08 28-13-27-22](https://user-images.githubusercontent.com/2035088/44722960-a0a1b980-aac6-11e8-91e2-248bcfd83a5e.png)

**Comment by vincent2090311** [comment]
@vseager 
Thank your for your report. The error already fixed in latest master branch

**Comment by davidwindell** [comment]
Thanks @vincent2090311, could you push up a new release?

**Comment by vincent2090311** [comment]
@davidwindell 
I pushed new release.

**Comment by davidwindell** [comment]
Thanks, could you update packagist (or setup the service hook in Github)? :+1:

**Comment by vincent2090311** [comment]
@davidwindell 
I migrated service to webhooks. Should be ok now
