### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by sebus208** [vincent2090311/magento2-campaignmonitor#3]
Hello, I have tried following your instructions to install the extension but i do not see Campaign Monitor at stores > Configuration

I have tried putting the files inside /app/code, inside /app/code/community/campaign-monitor and inside /app/code/campaign-monitor.

I have also tried deleting all static and cache files and then upgrading using the command.

`rm -rf var/di/*; rm -rf pub/static/*; rm -rf var/cache/*; rm -rf var/pagecache/*; rm -rf var/generation/*; rm -rf var/dir/*; rm -rf var/view_preprocessed/*; php bin/magento cache:flush && php bin/magento setup:upgrade && php bin/magento setup:static-content:deploy && php bin/magento setup:static-content:deploy nl_NL && php bin/magento indexer:reindex`

If i do `php bin/magento module:status` I cannot see Campaign Monitor.

I am using Magento 2.2.5 CE

Edit:
After moving the files into /httpdocs/app/code/Luma/Campaigmonitor I can see the plugin when i do `php bin/magento module:status` but when I do `php bin/magento setup:upgrade` I get the error  `[ReflectionException]                                   
  Class Luma\Campaignmonitor\Console\Sync does not exist`

**Comment by vincent2090311** [comment]
@sebus208 
I just updated installation instruction. Could you try again? I tried to install on my PC but its working fine

**Comment by sebus208** [comment]
Installing using composer works, thank you.
