### ISSUE TITLE
Magento 2.4 supported?

### ISSUE THREAD

**Issue by LiamTrioTech** [vincent2090311/magento2-campaignmonitor#7]
Hi is there any news or plans for updating this?

Magento 2.4 support.
Updated CreateSend dependency 6.1.1
PHP 7.4.

**Comment by LiamTrioTech** [comment]
I am seeing this API Test Error: Must supply a valid HTTP Basic Authorization header.
The code looks to be setting the auth to basic with null as a password however trying a dummy password such as 'x' also did not work.

![image](https://user-images.githubusercontent.com/68578009/102835805-99073b00-445c-11eb-9f50-121c8081df47.png)

**Comment by LiamTrioTech** [comment]
This problem is caused by the apiKey being urlencoded in getApiKey
https://github.com/vincent2090311/magento2-campaignmonitor/blob/a41cf0be142fe5eb4aece533b88863c25ea40bc5/Helper/Data.php#L145

Don't encode it here, do that in the code that shows it on the form if needed to urlencode.

After line 193 in CampaignMonitor.php decoding makes it work.

```php
$apiKey = urldecode($apiKey);
```

**Comment by stevenbrookes** [comment]
See #10 which fixes support for 2.4.3

**Comment by vincent2090311** [comment]
@LiamTrioTech @stevenbrookes 
I'm happy to announce that new package has been released to support newest magento version + CampaignMonitor API v3.3 + CreateSend PHP v7 here https://github.com/vincent2090311/cm2
